import math
from typing import Optional
from datetime import datetime, timezone

class ImportanceScorer:
    """Calculates dynamic importance of memories."""
    
    def __init__(
        self,
        w_recency: float = 0.25,
        w_frequency: float = 0.20,
        w_relevance: float = 0.30,
        w_emotional: float = 0.10,
        w_explicit: float = 0.15
    ):
        self.w_recency = w_recency
        self.w_frequency = w_frequency
        self.w_relevance = w_relevance
        self.w_emotional = w_emotional
        self.w_explicit = w_explicit
        
    def _recency_score(self, last_accessed_at: str) -> float:
        """0.0 to 1.0 based on how recently accessed."""
        if not last_accessed_at:
            return 0.0
            
        try:
            acc_time = datetime.fromisoformat(last_accessed_at)
            now = datetime.now(timezone.utc)
            hours = max(0, (now - acc_time).total_seconds() / 3600.0)
            
            # Decay recency score to half every 24 hours
            return math.exp(-0.0288 * hours)
        except Exception:
            return 0.0
            
    def _frequency_score(self, access_count: int) -> float:
        """0.0 to 1.0 based on log-scaled access count."""
        if access_count <= 0:
            return 0.0
        # cap at ~1000 accesses for max score
        return min(1.0, math.log10(access_count + 1) / 3.0)
        
    def score(
        self, 
        base_importance: float,
        access_count: int,
        last_accessed_at: str,
        emotional_weight: float = 0.0,
        relevance: float = 0.5,
        explicit: bool = False
    ) -> float:
        """Calculate total importance."""
        
        recency = self._recency_score(last_accessed_at)
        freq = self._frequency_score(access_count)
        explicit_score = 1.0 if explicit else 0.0
        
        # We blend the base importance generated by the model with the operational importance
        operational_importance = (
            self.w_recency * recency +
            self.w_frequency * freq +
            self.w_relevance * relevance +
            self.w_emotional * emotional_weight +
            self.w_explicit * explicit_score
        )
        
        # Combine base (model's view) and operational (usage view)
        return (base_importance * 0.4) + (operational_importance * 0.6)

    def score_extended(
        self,
        base_importance: float,
        access_count: int,
        last_accessed_at: str,
        emotional_weight: float = 0.0,
        relevance: float = 0.5,
        explicit: bool = False,
        # --- Extended signals ---
        user_explicit_boost: float = 0.0,    # 0-1: user directly flagged this memory
        agent_signal: float = 0.0,           # 0-1: agent recorded this as important
        reasoning_depth: int = 0,            # number of reasoning steps that used this
        knowledge_reuse_count: int = 0,      # times referenced across conversations
    ) -> float:
        """
        Extended importance scoring that incorporates agent, reasoning, and
        knowledge-reuse signals on top of the base operational score.

        Extended weights (after base score computed):
          user_boost       0.10
          agent_signal     0.12
          reasoning_depth  0.08  (log-scaled, capped at depth 10)
          knowledge_reuse  0.10  (log-scaled, capped at 100 uses)

        The total weight sum remains 1.0 by re-normalising the base operational
        portion to 0.60 and distributing the remaining 0.40 across extended signals.
        """
        base_score = self.score(
            base_importance=base_importance,
            access_count=access_count,
            last_accessed_at=last_accessed_at,
            emotional_weight=emotional_weight,
            relevance=relevance,
            explicit=explicit,
        )

        # --- Extended signal normalisation ---
        user_boost_score   = min(1.0, max(0.0, user_explicit_boost))
        agent_score        = min(1.0, max(0.0, agent_signal))
        reasoning_score    = min(1.0, math.log10(reasoning_depth + 1) / math.log10(11)) \
                             if reasoning_depth > 0 else 0.0
        reuse_score        = min(1.0, math.log10(knowledge_reuse_count + 1) / 2.0) \
                             if knowledge_reuse_count > 0 else 0.0

        extended_boost = (
            0.10 * user_boost_score +
            0.12 * agent_score +
            0.08 * reasoning_score +
            0.10 * reuse_score
        )

        # Scale base_score down slightly to make room for extended signals
        return min(1.0, base_score * 0.70 + extended_boost)
