"""
ALOY Search V2 — Data Transfer Objects (DTOs) and Models

Clean, type-annotated, validated, and serializable Pydantic models for the
Search V2 subsystem.
"""

from typing import List, Dict, Any, Optional
from datetime import datetime, timezone
from pydantic import BaseModel, Field, field_validator, model_validator, ConfigDict


class SearchIntent(BaseModel):
    """Represents the outcome of the search decision engine."""
    model_config = ConfigDict(extra="ignore")

    query: str = Field(..., min_length=1, description="Original user prompt or query")
    intent_type: str = Field(
        default="fast",
        description="Search path: 'fast', 'slow', 'none', 'followup', 'live', 'docs'"
    )
    requires_search: bool = Field(default=True, description="Whether live search is required")
    is_followup: bool = Field(default=False, description="Whether this query is a follow-up to prior search")
    confidence: float = Field(default=1.0, ge=0.0, le=1.0, description="Decision confidence score [0.0 - 1.0]")
    reasoning: Optional[str] = Field(default=None, description="Explanation for decision")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Additional intent metadata")

    @field_validator("query")
    @classmethod
    def validate_query_not_empty(cls, v: str) -> str:
        s = v.strip()
        if not s:
            raise ValueError("Query cannot be empty or whitespace only.")
        return s

    def to_dict(self) -> Dict[str, Any]:
        return self.model_dump()

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "SearchIntent":
        return cls.model_validate(data)


class QueryPlan(BaseModel):
    """Represents a planned set of search queries generated by the planner or fast-path fallback."""
    model_config = ConfigDict(extra="ignore")

    original_query: str = Field(..., min_length=1, description="Original user query")
    queries: List[str] = Field(default_factory=list, description="Search queries to execute")
    strategy: str = Field(default="single", description="Strategy: 'single', 'multi_hop', 'broadening', 'parallel'")
    required_providers: List[str] = Field(default_factory=lambda: ["duckduckgo"], description="Providers to query")
    max_results_per_query: int = Field(default=5, gt=0, description="Maximum results per query")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Planner metadata")

    @field_validator("original_query")
    @classmethod
    def validate_original_query(cls, v: str) -> str:
        s = v.strip()
        if not s:
            raise ValueError("Original query cannot be empty.")
        return s

    @model_validator(mode="after")
    def populate_queries_fallback(self) -> "QueryPlan":
        cleaned = [q.strip() for q in self.queries if q and q.strip()]
        if not cleaned and self.original_query:
            cleaned = [self.original_query]
        self.queries = cleaned
        return self

    def to_dict(self) -> Dict[str, Any]:
        return self.model_dump()

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "QueryPlan":
        return cls.model_validate(data)


class NormalizedResult(BaseModel):
    """Generic search result outputted by any ISearchProvider implementation."""
    model_config = ConfigDict(extra="ignore")

    title: str = Field(default="", description="Result title")
    url: str = Field(default="", description="Result URL")
    snippet: str = Field(default="", description="Result text snippet")
    provider: str = Field(default="unknown", description="Provider name (e.g. duckduckgo)")
    timestamp: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC"),
        description="Fetch timestamp in UTC"
    )
    raw_score: float = Field(default=0.0, ge=0.0, description="Raw provider score if available")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Provider specific raw metadata")

    def to_dict(self) -> Dict[str, Any]:
        return self.model_dump()

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "NormalizedResult":
        return cls.model_validate(data)


class RankedEvidence(BaseModel):
    """Ranked and sliced evidence snippet ready for context assembly."""
    model_config = ConfigDict(extra="ignore")

    title: str = Field(default="", description="Evidence title")
    url: str = Field(default="", description="Evidence source URL")
    snippet: str = Field(default="", description="Relevant sliced text snippet")
    score: float = Field(default=0.0, ge=0.0, le=100.0, description="Overall relevance score [0.0 - 100.0]")
    authority_score: float = Field(default=50.0, ge=0.0, le=100.0, description="Domain authority score")
    freshness_score: float = Field(default=0.0, ge=0.0, le=20.0, description="Freshness boost score")
    relevance_score: float = Field(default=0.0, ge=0.0, le=20.0, description="Keyword/vector relevance score")
    confidence_rating: Optional[str] = Field(default=None, description="'High', 'Medium', or 'Low'")
    provider: str = Field(default="unknown", description="Source provider name")
    timestamp: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC"),
        description="Timestamp of retrieval"
    )
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Evidence metadata")

    @model_validator(mode="after")
    def compute_confidence_rating(self) -> "RankedEvidence":
        if self.confidence_rating:
            cap = self.confidence_rating.capitalize()
            if cap in {"High", "Medium", "Low"}:
                self.confidence_rating = cap
                return self
        
        # Auto-compute based on total score
        if self.score >= 85.0:
            self.confidence_rating = "High"
        elif self.score >= 60.0:
            self.confidence_rating = "Medium"
        elif self.score > 0.0:
            self.confidence_rating = "Low"
        else:
            self.confidence_rating = "Medium"
        return self

    def to_dict(self) -> Dict[str, Any]:
        return self.model_dump()

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "RankedEvidence":
        return cls.model_validate(data)


class SearchContext(BaseModel):
    """Encapsulates the complete search state and output for prompt injection."""
    model_config = ConfigDict(extra="ignore")

    search_triggered: bool = Field(default=False, description="Whether search was executed")
    search_succeeded: bool = Field(default=False, description="Whether search yielded usable results")
    query: str = Field(default="", description="Target query executed")
    intent: Optional[SearchIntent] = Field(default=None, description="Intent decision")
    plan: Optional[QueryPlan] = Field(default=None, description="Query execution plan")
    results_count: int = Field(default=0, ge=0, description="Total evidence items retained")
    evidence: List[RankedEvidence] = Field(default_factory=list, description="Ranked evidence list")
    formatted_block: str = Field(default="", description="Final prompt context string for injection")
    confidence: float = Field(default=0.0, ge=0.0, le=1.0, description="Overall confidence score [0.0 - 1.0]")
    execution_time_ms: float = Field(default=0.0, ge=0.0, description="Total pipeline latency in ms")
    failure_reason: Optional[str] = Field(default=None, description="Failure reason if search_succeeded is False")

    def to_dict(self) -> Dict[str, Any]:
        return self.model_dump()

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "SearchContext":
        return cls.model_validate(data)
